### ISSUE TITLE
회사 포폴 포스터 사용가능함.

### ISSUE THREAD

**Issue by khw7096** [75mm-studio/web#97]
- 연도, 월
- 포스터: 참여작품 리스트 받기

**Comment by khw7096** [comment]
https://www.w3schools.com/howto/howto_css_image_grid_responsive.asp

마우스 올렸을 때 기본적인 설명이 뜨도록 하기.

**Comment by baesy0** [comment]
#### 위치
- 소개
- **작업리스트(포스터)**
- 특징(feature)
